- defaults:
    link:
      create: true
      relink: true

- clean: # cleans dead symbolic links
    - '~'

- link:
    ~/.bundle/config: bundle/config
    ~/.config/doom: doom
    ~/.config/nvim: nvim
    ~/.config/kitty:
      path: kitty
      force: true
    ~/.editorconfig:
    ~/.gvimrc:
    ~/.irbrc:
    ~/.tmux.conf:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:
      force: true
    ~/bin/serve: bin/serve

- create:
    - ~/Developer

- shell:
  - ["git submodule update --init --recursive", Installing submodules]
  - ["vim +PlugUpdate +PlugClean! +qa", Installing and updating plugins]
