image:
  file: .gitpod.Dockerfile

tasks:
  - prebuild: ./install.sh && vim +PlugInstall +qall > /dev/null
  - init: ./install.sh && vim +PlugInstall +qall > /dev/null
  - command: ./install.sh

github:
  prebuilds:
    addBadge: true
