
Vagrant.configure("2") do |config|

	if Vagrant.has_plugin? 'vagrant-cachier'
		#config.cache.auto_detect = true
		# If you are using VirtualBox, you might want to enable NFS for shared folders
		#config.cache.enable_nfs  = true
	end
	
	if Vagrant.has_plugin? 'vagrant-vbguest'
		#config.vbguest.no_install = true
		#config.vbguest.auto_update = false
	end

end
